title: Saurabh's analysis results
author: Saurabh Gandhi
email: gsaurabhr@gmail.com
description: > # this means to ignore newlines until "baseurl:"

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
