title: Saurabh's analysis results
author: Saurabh Gandhi
email: gsaurabhr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
# social links
github_username:  gsaurabhr

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-tactile
